name: AceVortex CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: cp ./gameart.png ./dist/acecombat7skiesunknown
    - uses: actions/upload-artifact@v1
      with:
        name: game-acecombat7skiesunknown
        path: dist/
